### ISSUE TITLE
Check live sites

### ISSUE THREAD

**Issue by chrisspen** [stephenmcd/django-shotgun#1]
This is an interesting project. Although you might want to consider allowing it to check a live database/website instead of only a unittest fixture. Like you mention, it's most useful to test against live data, and most sites I work with have a database over 1GB, so there's no feasible way to convert that into a fixture. Ideally, I'd like to login to my server, or at the very least load a production database snapshot onto a dev environment, and run something like 'manage.py check_for_505`, which will then do what your builtin test case doesn't, but check the URLs on a production site instead.

**Comment by stephenmcd** [comment]
Hey Chris,

If you'd like to submit a patch I'd happily merge it in.

We already have the SHOTGUN_ROOT_URL setting which you could certainly prefix with an absolute host, you'd just need a way for the test case class to swap out the client to something that speaks http.

**Comment by stephenmcd** [comment]
In fact you could probably check if SHOTGUN_ROOT_URL begins with a scheme (http or https) then it could automatically use python-requests as the client.

**Comment by stephenmcd** [comment]
Felt like doing this anyway :-) Please give it a spin.

**Comment by chrisspen** [comment]
Thanks for looking into this.
